/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Fri Sep  6 11:13:49 2019. */

#ifndef PB_MSG_PB_H_INCLUDED
#define PB_MSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Msg {
    bool has_content;
    pb_byte_t content[140];
    bool has_originatorNodeId;
    int32_t originatorNodeId;
    bool has_originatorBattLevel;
    int32_t originatorBattLevel;
    bool has_receiverRssi;
    int32_t receiverRssi;
    bool has_receiverSnr;
    float receiverSnr;
    bool has_receiverFreqErr;
    int32_t receiverFreqErr;
    bool has_receiverLat;
    float receiverLat;
    bool has_receiverLng;
    float receiverLng;
    bool has_senderLat;
    float senderLat;
    bool has_senderLng;
    float senderLng;
    bool has_originatorLat;
    float originatorLat;
    bool has_originatorLng;
    float originatorLng;
    bool has_receiverNodeId;
    int32_t receiverNodeId;
    bool has_senderTimeQuality;
    int32_t senderTimeQuality;
    bool has_originatorEpochTime;
    int32_t originatorEpochTime;
    bool has_receiverEpochTime;
    int32_t receiverEpochTime;
    bool has_senderEpochTime;
    int32_t senderEpochTime;
/* @@protoc_insertion_point(struct:Msg) */
} Msg;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Msg_init_default                         {false, {0}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Msg_init_zero                            {false, {0}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Msg_content_tag                          1
#define Msg_originatorNodeId_tag                 2
#define Msg_originatorEpochTime_tag              21
#define Msg_originatorBattLevel_tag              6
#define Msg_originatorLat_tag                    17
#define Msg_originatorLng_tag                    18
#define Msg_receiverNodeId_tag                   19
#define Msg_receiverRssi_tag                     7
#define Msg_receiverSnr_tag                      8
#define Msg_receiverFreqErr_tag                  9
#define Msg_receiverLat_tag                      10
#define Msg_receiverLng_tag                      11
#define Msg_receiverEpochTime_tag                22
#define Msg_senderLat_tag                        15
#define Msg_senderLng_tag                        16
#define Msg_senderTimeQuality_tag                20
#define Msg_senderEpochTime_tag                  23

/* Struct field encoding specification for nanopb */
extern const pb_field_t Msg_fields[18];

/* Maximum encoded size of messages (where known) */
#define Msg_size                                 285

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
